AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyUser:
    Type: AWS::IAM::User
    Properties:
      UserName: app-dev
    UpdatePolicy:
      Retain: true

  MyUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: MyUserPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:CreateBucket
              - s3:ListBucket
              - s3:GetBucketLocation
              - s3:DeleteBucket
              - s3:GetBucketPolicy
              - s3:PutBucketPolicy
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource: "*"
          - Effect: Allow
            Action:
              - sqs:CreateQueue
              - sqs:GetQueueAttributes
              - sqs:SetQueueAttributes
              - sqs:DeleteQueue
              - sqs:SendMessage
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
            Resource: "*"
          - Effect: Allow
            Action:
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:GetRepositoryPolicy
              - ecr:DescribeRepositories
              - ecr:ListImages
              - ecr:DescribeImages
              - ecr:BatchGetImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
              - ecr:PutImage
              - ecr:CreateRepository
              - ecr:DeleteRepository
            Resource: "*"
          - Effect: Allow
            Action:
              - iam:GetRole
              - iam:CreateRole
              - iam:PutRolePolicy
              - iam:DeleteRolePolicy
              - iam:GetRolePolicy
              - iam:DeleteRole
              - iam:PassRole
            Resource: "*"
          - Effect: Allow
            Action:
              - codebuild:CreateProject
              - codebuild:DeleteProject
            Resource: "*"

          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource: "*"
          - Effect: Allow
            Action: 
              - lambda:GetFunction
              - lambda:DeleteFunction
              - lambda:CreateFunction
            Resource: "*"
          - Effect: Allow
            Action:
              - cloudformation:DescribeStacks  
              - cloudformation:CreateChangeSet
              - cloudformation:CreateStack
              - cloudformation:ExecuteChangeSet
              - cloudformation:DescribeChangeSet
            Resource: "*"
      Users:
        - Ref: MyUser