AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyUser:
    Type: AWS::IAM::User
    Properties:
      UserName: app-dev

  MyUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: MyUserPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:CreateBucket
            Resource: "*"
          - Effect: Allow
            Action:
              - sqs:CreateQueue
            Resource: "*"
  #        - Effect: Allow
  #          Actions:
  #            - cloudformation:DescribeStacks
   #         Resource: "*"
      Users:
        - Ref: MyUser
